[package]
name = "de_geometry"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
repository = "https://github.com/DigitalExtinction/Game"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
glam = "0.20.2"
approx = "0.5.1"
