[package]
name = "de"
version = "0.1.0-dev"
edition = "2021"
authors = ["Martin Indra <martin.indra@mgn.cz>"]
readme = "README.md"
repository = "https://github.com/Indy2222/Digital-Extinction"

[dependencies]
# DE
de_game = { path = "crates/game", version = "0.1.0-dev" }
de_gui = { path = "crates/gui", version = "0.1.0-dev" }

# Other
bevy = "0.7.0"

[workspace]
members = ["crates/*"]
